[package]
name = "tiny"
version = "0.1.0"
edition = "2021"

[lib]
name = "tiny"
path = "src/tiny/lib.rs"

[[bin]]
name = "sokoban"
path = "src/sokoban/bin.rs"

[[bin]]
name = "snake"
path = "src/snake/bin.rs"

[dependencies]
termios = "0.3"